baseURL = "https://nguyenducleminh11-pixel.github.io/My-blog/"
title = "lminhnd"
theme = "PaperMod"

# Ngôn ngữ mặc định
defaultContentLanguage = "vi"

[languages]
    [languages.vi]
        languageName = "Tiếng Việt"
        contentDir = "content/vi"
        weight = 1
        [languages.vi.menu]
            [[languages.vi.menu.main]]
                name = "Giải Thuật"
                url = "problems"
                weight = 10
            [[languages.vi.menu.main]]
                name = "Thủ Thuật"
                url = "tips"
                weight = 20
            [[languages.vi.menu.main]]
                name = "Nhật Ký"
                url = "daily"
                weight = 30
            [[languages.vi.menu.main]]
                name = "Tìm kiếm"
                url = "search"
                weight = 40

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    env = "production"
    title = "lminhnd"
    description = "Blog cá nhân chia sẻ kiến thức"
    author = "lminhnd"
    
    # Giao diện List (giống Codeforces Feed)
    displayFullLangName = true
    showCodeCopyButtons = true
    
    # CHỖ NÀY QUAN TRỌNG: 
    # Để false để trang chủ hiện tiêu đề + ảnh bìa + tóm tắt (nhìn rất Pro)
    showFullContents = false 
    
    # Tự động lấy bài từ 3 mục này đẩy ra trang chủ
    mainSections = ["daily", "problems", "tips"]

    # Cấu hình ảnh bìa cho các bài viết
    [params.cover]
        responsiveImages = true
        linkFullImages = false
